### ISSUE TITLE
Let user choose a testing framework?

### ISSUE THREAD

**Issue by sergzbx** [yeoman/generator-node#100]
Is it possible to add an option which framework to use for testing?

* [ ] Mocha
* [ ] TAP
* [ ] Jasmine
* [ ] qUnit
* [ ] ...

**Comment by stevemao** [comment]
I think this is way less important than #66

**Comment by arthurvr** [comment]
On the idea itself, I guess it's something users want, but it would complicate our setup quite a bit.

> I think this is way less important than #66

Yes we should try to hold off on implementing new features till that happened.

**Comment by arthurvr** [comment]
So what's the status of this? Do we even want it? It seems like a bunch of work to maintain while most people would still go with the default. At Yeoman, we don't need anything more than mocha anyways.

> qUnit

It's possible after a bunch of tweaking but QUnit isn't ideal to test Node modules. It's fairly uncommon as well.

**Comment by stevemao** [comment]
I agree, don't think this is very important.
