### ISSUE TITLE
Raw build system option

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#111]
We could base ourselves on yeoman-environment who's not using Gulp. (see https://github.com/yeoman/environment/commit/d89bdc3a7888d303b485233b5cb0ee597cd624e9#commitcomment-9690814)

**Comment by hemanth** [comment]
`npm run scripts` I would vote for bash as well. :+1:

**Comment by stevemao** [comment]
`npm run scripts`
but if it gets too complex then shell

**Comment by stevemao** [comment]
I think if user doesn't choose a build system, the project is usually simple so the structure could be simpler: instead of having `/lib/`, `/test/` and `/bin/` folders it should be just flattened, just like https://github.com/sindresorhus/generator-nm. In fact a lot of times I just move those files manually after everything is generated. It would be great to flatten the file structure if no build system is selected.

**Comment by robbbz** [comment]
> npm run scripts I would vote for bash as well. :+1:

Npm scripts, but not bash. Bash isn't cross platform, only the part [npm shims](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/#thewindowsproblem) is.

**Comment by twixie** [comment]
:+1: 

> Npm scripts, but not bash. Bash isn't cross platform, only the part npm shims is.

yes :) i think @hemanth just meant that.

**Comment by iamstarkov** [comment]
votштп for npm-scripts versions. I chose them it turns out very well https://github.com/iamstarkov/generator-tiny-es-nm/blob/master/app/templates/_package.json#L6-L17

**Comment by iamstarkov** [comment]
I can make pull-request to bring support of raw build system here. should I?

**Comment by SBoudrias** [comment]
@iamstarkov PR is welcomed!

**Comment by iamstarkov** [comment]
I tried yesterday, but failed. the scope is very broad, should I replicate gulp flow? which step should be replicated?

**Comment by SBoudrias** [comment]
@iamstarkov test + coverage + nsp check.

We should probably drop babel from the raw build.

**Comment by iamstarkov** [comment]
I planned to respect babel option in the raw build. is it ok?

**Comment by SBoudrias** [comment]
@iamstarkov If someone wants a raw build system, I assume they'd want simplicity - and that's not babel.

**Comment by iamstarkov** [comment]
@SBoudrias but maybe they want es2015 goodies too. for example me. so if you dont mind ill try later this week to implement it again. thank you for response about pr scope.

**Comment by arthurvr** [comment]
I agree with @iamstarkov, the complexity of adding Babel is still way less than having a complete Gulp build workflow.

**Comment by iamstarkov** [comment]
@SBoudrias @arthurvr as a followup i have a question, because i tried to add pure build support without removing gulp deps and it turned out to be quite messy: right now its only two branches gulp with or without es2015, if we are adding pure build then its become 4 branches: gulp or pure with or without babel. its quite complex. so the question is: why did generator node need gulp dev-flow in the first place?

**Comment by iamstarkov** [comment]
can anybody show yo generator wtth ava tests?

**Comment by SBoudrias** [comment]
> why did generator-node need gulp dev-flow in the first place?

With mocha and istanbul, that's the easiest setup (sure beats the cli). Also, windows doesn't have `&&` support in their cli.

**Comment by iamstarkov** [comment]
there are possible solutions for `&&` problem like:
* `npm pre/post scripts` for simple scripts
* [npm-run-all](http://npmjs.com/package/npm-run-all) to run complicated scripts

**Comment by stevemao** [comment]
@iamstarkov see https://github.com/sindresorhus/xo-init/issues/3 and https://github.com/sindresorhus/xo-init/pull/6

**Comment by iamstarkov** [comment]
@stevemao dont really get what you wanted to point out

**Comment by stevemao** [comment]
Those issues are discussing `npm pre/post scripts` and `&&` problem etc.

**Comment by iamstarkov** [comment]
yeah, i got that part and as i far as i understood `pre/post scripts` are doing better than `&&`

**Comment by SBoudrias** [comment]
Since v2.0, this ticket is now un-relevant. We don't use gulp anymore :)
