### ISSUE TITLE
Missing cli and browserify options

### ISSUE THREAD

**Issue by stevemao** [yeoman/generator-node#112]
Is it intentional? I think the cli option is quite useful.

**Comment by SBoudrias** [comment]
We could re-add cli option.

But browserify is out of scope, this is for node modules, not browsers.

**Comment by stevemao** [comment]
Would it be in a submodule?

**Comment by arthurvr** [comment]
Just PR'd. @SBoudrias Do you want to review #122 please? Thanks.
