### ISSUE TITLE
Babel support is missing

### ISSUE THREAD

**Issue by stevemao** [yeoman/generator-node#114]
#110 is not in the git history. Where is it? :sob:

**Comment by SBoudrias** [comment]
weird, it's not fixed.

**Comment by stevemao** [comment]
0513e60f908f11d97750cba5d6ae1bda08f60974

**Comment by stevemao** [comment]
Can you make a release?

**Comment by SBoudrias** [comment]
Done

**Comment by stevemao** [comment]
Thank you :smile: , gonna play with it.
