### ISSUE TITLE
npm test fails on scaffolded project

### ISSUE THREAD

**Issue by petersandor** [yeoman/generator-node#121]
When I run `npm test` in the freshly scaffolded project directory, I get the following error:
```
λ npm test

> test-module@0.0.0 test C:\Projects\test-module
> gulp

[12:13:42] Using gulpfile C:\Projects\test-module\gulpfile.js
[12:13:42] Starting 'static'...
[12:13:42] Starting 'pre-test'...

C:\Projects\test-module\gulpfile.js
  line 2  col 5  'path' is defined but never used.

  ‼  1 warning

[12:13:43] Finished 'pre-test' after 216 ms
[12:13:43] Starting 'test'...

C:\Projects\test-module\test\index.js
  line 5  col 3  Missing "use strict" statement.
  line 2  col 8  'testModule' is defined but never used.

  ×  1 error
  ‼  1 warnings


events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: JSHint failed for: C:\Projects\test-module\gulpfile.js, C:\Projects\test-module\test\index.js
npm ERR! Test failed.  See above for more details.
```
Can someone please take a look this? Thanks.

**Comment by arthurvr** [comment]
Thanks for reporting. I'll fix those this evening.

**Comment by addyosmani** [comment]
Confirmed. Thanks for reporting! Apprec you being down for fixing, @arthurvr!

**Comment by arthurvr** [comment]
> Missing "use strict" statement.

Hmm so this is kind of a tricky one. We don't add `use strict` when using babel as babel adds that automatically. We could just remove the `strict` JSHint option when using babel but maybe we should just add `use strict` always? Even if it's just for explicitness (and not having it might confuse people).

**Comment by SBoudrias** [comment]
I believe we should always add it for explicitness. ES6 doesn't remove strict mode and it's usefulness.

We should see the Babel branch as the es6 (and +) branch - not the Babel branch.

**Comment by arthurvr** [comment]
Agreed.

> 'testModule' is defined but never used.

This is kinda another tricky one. I don't want to set `undef` to false as people might not remove that anymore. In the past we fixed this by just [calling the function](https://github.com/yeoman/generator-node/blob/a0ea6fdc8e0e8667524f91ab090b5d37d64d9ee5/app/templates/test/test.js#L8).

Should I do the same thing now? It might look a little strange but then it would end up like:

```js
describe('<%= pkgName %>', function () {
  it('should have unit test!', function () {
    <%= pkgSafeName %>;
    assert(false, 'we expected this package author to add actual unit tests.');
  });
});
```

Any better suggesstions?

**Comment by SBoudrias** [comment]
@arthurvr I'm okay with this line reporting an error on initial build. The test is not written, it's totally normal jshint would complain.
