### ISSUE TITLE
JSCS + ES2015

### ISSUE THREAD

**Issue by arthurvr** [yeoman/generator-node#123]
Our current JSCS setup doesn't work well with ES2015 (and thus not with the babel option). If you choose to include babel it fails and reports syntax errors.

Also, if you the `dist` directory is present it lints that directory too.

**Comment by arthurvr** [comment]
Unrelated but how about us just switching to ESLint? We made the switch at generator-gulp-webapp as well.

**Comment by SBoudrias** [comment]
JSCS is not the same as ESLint. It parse code style, not linting.

**Comment by stevemao** [comment]
ESLint checks both code style and linting.

**Comment by arthurvr** [comment]
> ESLint checks both code style and linting.

[Yes](https://github.com/eslint/eslint#is-eslint-just-linting-or-does-it-also-check-style).

**Comment by SBoudrias** [comment]
I know we dropped ESLint on yeoman-generator, because it kept breaking our Travis integration because breaking linting rules were changing in minor release.

If you think it's more stable now (I don't think so), feel free to give it a try.

**Comment by arthurvr** [comment]
Well, do we even have much of a choice? JSCS doesn't even support ES2015 syntax completely.

> If you think it's more stable now (I don't think so), feel free to give it a try.

It's getting better and better daily from what I can tell.

**Comment by robbbz** [comment]
I'm +1 to switching to ESLint where possible. Also other generators please. JSHint and JSCS aren't stable too.

**Comment by SBoudrias** [comment]
@robbbz Want to work on a PR for this one?

**Comment by arthurvr** [comment]
> because it kept breaking our Travis integration because breaking linting rules were changing in minor release.

By the way, ESLint is still at `0.x.x` versions so that's perfectly valid.

**Comment by robbbz** [comment]
I will do that.

**Comment by SBoudrias** [comment]
> By the way, ESLint is still at 0.x.x versions so that's perfectly valid.

That's not valid as it meant breaking changes where release in patches.

**Comment by robbbz** [comment]
Is JSCS/JSHint support still meant to be optional or do we just use ESLint?

> because it kept breaking our Travis integration because breaking linting rules were changing in minor release.

In minor bumps they can introduce breaking changes according to semantic versioning. You can read the specification on it on this website: http://semver.org/.

**Comment by SBoudrias** [comment]
@robbbz I was specifically speaking about patches versions. If things broke after we bump a version, that's fine. They were breaking when we just re-run our tests (so no version change on our side).

If we go with ESLint, we go all the way (so dropping jshint and jscs)

**Comment by robbbz** [comment]
> I was specifically speaking about patches versions. If things broke after we bump a version, that's fine. They were breaking when we just re-run our tests (so no version change on our side).

Oh okay. I believe it's better now though. Also I think you won't disagree that JSHint and JSCS aren't a good solution too.



> If we go with ESLint, we go all the way (so dropping jshint and jscs)

I'll keep that in mind.
