### ISSUE TITLE
npmName check bug: True/False behaviours are reversed

### ISSUE THREAD

**Issue by Oblongmana** [yeoman/generator-node#125]
When a name is taken in `npm`, you will NOT be re-prompted to choose a new name (`npmName(answers.name) === false`)
When a name is available in `npm`, you will be re-prompted to choose a new name (`npmName(answers.name) === true`)

This is happening in a fresh install of node, npm, yeoman, and generator-node, on OSX 10.10.3

In line 72 of `index.js`, `done(...)` is directly provided the result of the call to `npmName(answers.name)`. So the `done(...)` function is given `true` when a name is available - but `true` being provided to `done(...)` indicates the question should be asked again - so the solution is just flipping this boolean.

Will have an incredibly brief PR submitted shortly!

Hopefully I'm not missing something obvious or seeing atypical behaviour (wrong version of something, or something), feel free to let me know here or in the PR if I am!

**Comment by Oblongmana** [comment]
As touched on in PR, slightly misunderstood the issue - fix involves calling `done()` when ready to proceed, `done(true)` to re-prompt if name is already taken in npm

**Comment by robbbz** [comment]
Ah! Thanks for the fix. I updated and it was working again.
