### ISSUE TITLE
Get repository info from .git if it exists

### ISSUE THREAD

**Issue by danielchatfield** [yeoman/generator-node#13]
Currently `generator-node` populates the `repository` field in `package.json` using the username which is prompted for and the package name. Often the github repo name and the npm package name are different. I think it would be better to check whether the target directory is a git repo and then get the repo url from either `.git/config` or `.git/FETCH_HEAD`. If it isn't a git repository then fall back to asking the user for their username and guessing repo name.

**Comment by hemanth** [comment]
//cc @SBoudrias What say?

**Comment by robbbz** [comment]
Isn't this done in the new version?

**Comment by SBoudrias** [comment]
It is not done.

**Comment by SBoudrias** [comment]
There's also `var gitConfig = require('git-config');` which seems fairly easy to use. It's [used in generator-license](https://github.com/jozefizso/generator-license/blob/master/app/index.js#L33-L34)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/git-remote-origin-url might help.
