### ISSUE TITLE
Unclear how to use options (or they're broken)

### ISSUE THREAD

**Issue by theGrue** [yeoman/generator-node#130]
Was going to start a new project, but updated my generator and spent an hour Googling for this before giving up. I used to be prompted for things like a CLI, but now it is always created. The "Options" section of the documentation makes it sound like it is possible to disable this, but I can't seem to figure out how to actually use the option. I've tried all kinds of different ways to specify it:
* `yo node --cli=false`
* `yo node --cli="false"`
* `yo node --cli=no`
* `yo node --cli false`
* `yo node --cli`
* `yo node cli=false`

None of these work, and I always end up with a `lib/cli.js` file. How am I supposed to specify this option? Is it just broken, or is there a syntax I haven't guessed yet?

**Comment by SBoudrias** [comment]
Hi, to pass a negative option, you'd do it like `--no-cli`. Note though that the cli shouldn't be created by default, this is a bug. We'll fix it.

**Comment by theGrue** [comment]
Well I'll be damned, I never would have guessed that! Definitely seems worth having in the readme somewhere. Thanks for your help!

**Comment by SBoudrias** [comment]
BTW, it's fixed on the latest version.

**Comment by robbbz** [comment]
The options system as-is here is something that needs many documentation updates. The only thing documentation touches on are prompts.
