### ISSUE TITLE
Missing package name in CLI submodule

### ISSUE THREAD

**Issue by petersandor** [yeoman/generator-node#133]
I scaffolded a new node package and after adding a CLI submodule (`yo node:cli` or `yo node:cli customname`) I get `cli.js` with missing stuff (see `var = require('./')` and help string).

```js
#!/usr/bin/env node
'use strict';
var meow = require('meow');
var = require('./');
var pkg = require('../');

var cli = meow({
  pkg: pkg,
  help: [
    'Usage',
    '  $  [input]',
    '',
    'Examples',
    '  $ ',
    '  unicorns',
    '',
    '  $  rainbows',
    '  unicorns & rainbows',
    '',
    'Options',
    ' --foo Lorem ipsum. Default: false'
  ]
});
```

~~I found a solution,~~ see my PR https://github.com/yeoman/generator-node/pull/132

**Comment by SBoudrias** [comment]
We should save the app name provide to the main generator into a config (`this.config.set('appname', 'foo')`). Then we can reuse this value throughout the process.

**Comment by petersandor** [comment]
App name is available in [base generator class](https://github.com/yeoman/generator/blob/master/lib/base.js#L152) as `this.appname`. That's what I used in my fix, but I think that would remove the functionality of `--name`. 

As I mentioned in the PR, I think solving these would help:
1. Mention `--name` in subgenerator `--help `
2. If `--name` isn't provided, use `this.appname` as a default

**Comment by SBoudrias** [comment]
Made the name options required so this will fix the missing data for now. We still fix it better, so let's leave the issue open.
