### ISSUE TITLE
If babel is used, add a `prepublish` script

### ISSUE THREAD

**Issue by robbbz** [yeoman/generator-node#135]
@SBoudrias You forgot to add a prepublish script, the `dist` files don't get generated.

**Comment by arthurvr** [comment]
Ah, that sounds right. The dist folder also needs to be added to the `files`.

**Comment by SBoudrias** [comment]
Yeah, we missed a lot of nits adding Babel and the cli modules.

Thanks for reporting the issues. We'll fix them ASAP.

**Comment by sindresorhus** [comment]
Should be tested too to ensure we don't introduce regressions in the future ;)

**Comment by SBoudrias** [comment]
Added the prepublish step.
