### ISSUE TITLE
JShint shouldn't raise issues when parsing es2015 code

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#140]
Currently this is failing. That's kind of related to #123, but this issue is probably going to take a while, so let's make sure we're fixing JSHint ASAP.

**Comment by robbbz** [comment]
> That's kind of related to #123, but this issue is probably going to take a while, so let's make sure we're fixing JSHint ASAP.

I will not let it take a while. Promised a PR so working on that.

**Comment by hemanth** [comment]
:+1:
