### ISSUE TITLE
Don't include Babel by default

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#141]
This should be an option, and default to `false`.

**Comment by arthurvr** [comment]
:-1: I like it being default, I don't see why not.

**Comment by robbbz** [comment]
:-1:. Similar to @arthurvr I don't see why.

For small modules i agree babel should not be the default, but, this generator is more for use in bigger modules. smaller few-lines modules just use [generator-nm](https://github.com/sindresorhus/generator-nm) and you should assume something scalable by default.

The babel community is awesome, @thejameskyle was even keen enough to contribute a pull request, babel is really stable, and I didn't see anybody else who didn't like it.

Also, Babel just adds little overhead to the gulp setup and it's back-wards compatible with people that use ES5.

> This should be an option, 

It already is optional but just defaults to true. I don't really think it should've been an option eighter.

**Comment by twixie** [comment]
:-1: on not having it as default but it should be optional.

**Comment by twixie** [comment]
Don't take my -1 bad @SBoudrias. PS: have you had a chance to look at my environment pr yet?

**Comment by SBoudrias** [comment]
I'm sorry to feel very strongly about having it off by default.

My main issue is that ES2015 is not currently the supported language for node. ES5 is the official language. I think the only reasonable thing to do if we want to be *the* Node.js module generator is to stick with the officially supported language by Node.js. When v8 is updated and Node support es2015 out of the box, then it'll be the right time to update our generator. But for now, let's stick with the official language - and what we know works well.

Babel might be a pretty stable tool, but honestly just look at the number of issues we've had this week. We can fix these issues, but truth is supporting a precompilation step before being able to run tests or deploy a module creates a more error prone workflow.

When I say not support it by default, I doesn't mean hide the feature behind a `--babel` flag. Let's add a prompt asking for the user decision. But let's not silently add it as the default option.

I still believe Babel and es2015 are not ready for global deployment. The tools and the platform ecosystem are not 100% there yet. And until it is, it is not reasonable for us to make it our default scaffolding.

**Comment by thejameskyle** [comment]
Hey @SBoudrias really sorry you've been having a lot of issues related to Babel. I'd like to help out in any way that I can.

> I still believe Babel and es2015 are not ready for global deployment. The tools and the platform ecosystem are not 100% there yet. And until it is, it is not reasonable for us to make it our default scaffolding.

This is something we've worked very hard on over the past year, and at this point I'm going to have to disagree that the ecosystem isn't there. Linting, testing, code coverage, deploying and all the rest are solved issues.

Certain things need a little bit of special attention, and in some cases [out-of-date tools need to be swapped out for newer ones](https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48). But there's very little that has not already been considered. We just need to do a better job of communicating the work that's already been done.

I can contribute a couple of PRs related to this if you'd like. Even if you want to turn Babel off by default, I think there should be a rock solid setup here out of the box.

**Comment by robbbz** [comment]
> Babel might be a pretty stable tool, but honestly just look at the number of issues we've had this week.

None of the issues last week was related to the stability of babel and its tooling. the problem was that it wasn't integrated properly.

> My main issue is that ES2015 is not currently the supported language for node. ES5 is the official language. I think the only reasonable thing to do if we want to be the Node.js module generator is to stick with the officially supported language by Node.js.

the official Node generator should stick to what the community likes, not to what the language supports. Just like the webapp generator adds Sass, which isn't supported by browsers. Node **will** support these features in the future.

This isn't about having a precompiler on (or at least not a classical case of that), because the it only adds features which will be native implemented in a few months.

**Comment by SBoudrias** [comment]
Moved the option to a prompt. It is still on by default, but that choice is now clearly stated.

User won't end up with a es2015 project by surprise.
