### ISSUE TITLE
Run nsp audit-package as pre-publish script

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#145]
As with most yeoman core project, we should run a security audit of the packages used by our module -> `nsp audit-package`.

On our projects we run it as a pre-publish script. We could also add it as a test script.

I'm not sure if it's worth moving to a gulp task? https://github.com/nodesecurity/gulp-nsp

**Comment by sindresorhus** [comment]
> I'm not sure if it's worth moving to a gulp task? https://github.com/nodesecurity/gulp-nsp

Nah, easier to just have it in the npm run script.

**Comment by SBoudrias** [comment]
I went with the gulp task because adding as prepublish script was a bit tedious to handle when we needed to combine with the babel prepublish hooks.
