### ISSUE TITLE
Help user setup third party after code generation

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#146]
Once the project generation is done, there's 3 third party services the user would need to setup to get started:
- Travis
- Coveralls
- Github

What would be the easiest way to help our user setup these third services?

Should we automatically open the links to the activation page for each services?

**Comment by arthurvr** [comment]
> Should we automatically open the links to the activation page for each services?

I think that's the right thing to do, yeah. Using their APIs we *might* be able to setup everything for them automatically, but I don't think anybody wants to give a generator tokens for those services, and that would be a little overhead.

**Comment by stevemao** [comment]
Just ask user to type 
```
travis enable
hub create
```
Instead of accessing their api?

**Comment by SBoudrias** [comment]
@stevemao but then you still require our users to install these command line tools. I'm not sure that would be actually simpler, no?

**Comment by stevemao** [comment]
I think command line tools are simpler. Like @arthurvr mentioned its too much overhead. These command line tools are actively maintained officially so that you don't need to worry about it (say their api has changed etc). Also I'm sure these tools can do more and better than this module.

Personally I think this module should just focus on scaffolding a project and leave other jobs to better tools.

**Comment by arthurvr** [comment]
Although I do agree that it would be cool if the generator would be able to do this, think about how it would need to: it needs a token for both Travis and GitHub, those tokens need to have the right permissions, you have to input those tokens in some *secure* way, ...

I don't really like that option too, but that makes me think `hub create && travis enable` is way easier.

**Comment by SBoudrias** [comment]
I'm not sure where it's been said we'd automatically do it.

The point of this CR is to provide our users with the next step, what do they need to do to have these services working? The goal is to unblock our user and give them resource to go on with the manual step they need to take.

This might be:
- automatically opening the right page in their browser
- logging explanation of the steps to take
- etc

**Comment by iamstarkov** [comment]
"Next steps" list in a readme can help a lot https://www.npmjs.com/package/generator-tiny-es-nm#next-steps

**Comment by hemanth** [comment]
@SBoudrias Now that we have basic support for `travis`, `coverall` and `github`, this issue can be closed?

**Comment by SBoudrias** [comment]
No, we're not yet giving any follow up information on where to go to enable coveralls or travis.
