### ISSUE TITLE
How should we reliably handle line ending

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#150]
I don't think this is something we need to fix urgently, but I want to bring it up.

So, we don't want to force EOL to LF inside `.editorconfig` because this always conflict with git line ending normalization and mess up some windows tool. I know it's shitty, but I've been there and handling this while you work on windows is a nightmare. Let's be responsible and fix it correctly.

In almost any cases, we don't care whether we have LF or CRLF. The only case where it does matter is for `cli.js` because CRLF will break bash script.

I'd like us to have a foolproof prepublish hook that will ensure us correct package publication.

**Comment by hemanth** [comment]
I would also vote for `prepublish` hook.

**Comment by twixie** [comment]
Why can't we just don't care and use LF? That is what git converts it to any ways. Starting from the following major of Git that will even be the requirement (not optional).

**Comment by SBoudrias** [comment]
@twixie Git only normalize on commit, not checkout. And you publish to npm from your computer, not from the code inside a git repo.

So even if we "force" LF, that won't change anything and some people will still get it wrong.

**Comment by zckrs** [comment]
Maybe something like [gulp-line-ending-corrector](https://www.npmjs.com/package/gulp-line-ending-corrector) with prepublish task

**Comment by SBoudrias** [comment]
@hemanth why did you close this issue?

**Comment by hemanth** [comment]
Ha, ok. I related this issued with [this](https://github.com/yeoman/generator-node/commit/ce79de24a0ee245ccbabd96317795ebe0e29957c) fix.

**Comment by hemanth** [comment]
`gulp-line-ending-corrector` seems like a good idea.
