### ISSUE TITLE
Enforce styleguide with ESLint

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#153]
We're currently missing lots of style rules in ESLint, we need to improve this.

A good starting point is to base ourselves on the [JSCS rules from yeoman/generator](https://github.com/yeoman/generator/blob/master/.jscsrc).

I'll edit this ticket with new rules we want to enforce as we investigate and find the missing parts.

**Comment by IanVS** [comment]
If you'd like some help identifying ESLint rules, let me know and I'd be happy to help.

**Comment by SBoudrias** [comment]
@IanVS Any help is welcomed, just send a PR!

**Comment by IanVS** [comment]
I'm not sure I'll have bandwidth for that, but I'm on the ESLint team and can help answer questions you might have.  I also wrote [eslint-nibble](https://github.com/IanVS/eslint-nibble) to help when adding ESLint to a project.  After you set up rules you think you might want to use, you can run it and first you'll get the total number of errors and warnings across all your files per rule, and then you can focus in on a specific rule.  May or may not be useful for you.

We are also working on an "autoconfig" option within ESLint which will examine your code and determine the best rules to set to match the styles you're already using.  That's not ready yet though, unfortunately.

**Comment by zckrs** [comment]
#### Match between [Yeoman JSCS rules](https://github.com/yeoman/generator/blob/master/.jscsrc) and ESLint rules:

* requireCurlyBraces: [curly](http://eslint.org/docs/rules/curly#rule-details)
* requireSpaceAfterKeywords: [space-after-keywords](http://eslint.org/docs/rules/space-after-keywords#rule-details)
* requireSpacesInFunctionExpression: [space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren#rule-details)
* disallowMultipleVarDecl: [one-var](http://eslint.org/docs/rules/one-var#rule-details)
* disallowSpacesInsideArrayBrackets: [array-bracket-spacing](http://eslint.org/docs/rules/array-bracket-spacing#rule-details)
* disallowSpacesInsideParentheses: [space-in-parens](http://eslint.org/docs/rules/space-in-parens#rule-details)
* disallowSpaceAfterObjectKeys: [key-spacing](http://eslint.org/docs/rules/key-spacing#rule-details)
* disallowQuotedKeysInObjects: [quote-props](http://eslint.org/docs/rules/quote-props#rule-details)
* requireSpaceBeforeBinaryOperators: [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* disallowSpaceAfterBinaryOperators: [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* requireSpaceAfterBinaryOperators: [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* disallowSpaceBeforeBinaryOperators: [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* disallowSpaceAfterPrefixUnaryOperators: [space-unary-op](http://eslint.org/docs/rules/space-unary-ops#rule-details)
* disallowSpaceBeforePostfixUnaryOperators: [space-unary-op](http://eslint.org/docs/rules/space-unary-ops#rule-details)
* requireSpaceBeforeBinaryOperators: [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* requireSpaceAfterBinaryOperators: [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* disallowImplicitTypeConversion: **not found**
* disallowKeywords: [no-eval](http://eslint.org/docs/rules/no-eval#rule-details), [no-with](http://eslint.org/docs/rules/no-with#rule-details)
* disallowMultipleLineBreaks: [no-multiple-empty-lines](http://eslint.org/docs/rules/no-multiple-empty-lines#rule-details)
* disallowKeywordsOnNewLine: **not found**
* requireLineFeedAtFileEnd: [eol-last](http://eslint.org/docs/rules/eol-last#rule-details)
* excludeFiles: [use .eslintignore file](http://eslint.org/docs/user-guide/configuring.html#ignoring-files-and-directories)
* validateIndentation: [indent](http://eslint.org/docs/rules/indent#rule-details)

#### Already enabled by default ESLint configuration

* [curly](http://eslint.org/docs/rules/curly#rule-details)
* [key-spacing](http://eslint.org/docs/rules/key-spacing#rule-details)
* [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* [space-infix-ops](http://eslint.org/docs/rules/space-infix-ops#rule-details)
* [no-eval](http://eslint.org/docs/rules/no-eval#rule-details)
* [no-with](http://eslint.org/docs/rules/no-with#rule-details)
* [eol-last](http://eslint.org/docs/rules/eol-last#rule-details)

#### Currently set by `generator/eslint`

* [strict](http://eslint.org/docs/rules/strict#rule-details)
* [quotes](http://eslint.org/docs/rules/quotes#rule-details)
* [indent](generators/eslint/index.js#L21)
* [one-var](generators/eslint/index.js#L22)
* [consistent-return](http://eslint.org/docs/rules/consistent-return#rule-details) See https://github.com/yeoman/generator-node/pull/151#discussion_r35198283 
* [no-use-before-define](http://eslint.org/docs/rules/no-use-before-define#rule-details) 
* [space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren#rule-details)

#### Not yet (off by default)

* [space-after-keywords](http://eslint.org/docs/rules/space-after-keywords#rule-details)
* [array-bracket-spacing](http://eslint.org/docs/rules/array-bracket-spacing#rule-details)
* [space-in-parens](http://eslint.org/docs/rules/space-in-parens#rule-details)
* [quote-props](http://eslint.org/docs/rules/quote-props#rule-details)
* [no-multiple-empty-lines](http://eslint.org/docs/rules/no-multiple-empty-lines#rule-details)

***
PR in progress.

@IanVS do you know equivalent rules for "disallowImplicitTypeConversion" and "disallowKeywordsOnNewLine"?

**Comment by IanVS** [comment]
> Already enabled by default ESLint configuration
- curly
- key-spacing
- space-infix-ops...

Keep in mind that in the rapidly approaching v1.0.0 release, no rules will be enabled by default.  As such, I would recommend explicitly specifying them now to make the transition easier.

For `disallowImplicitTypeConversion`, a rule was created 11 days ago named [no-implicit-coercion](http://eslint.org/docs/1.0.0/rules/no-implicit-coercion).  It is landing in version 1.0 (which is in [rc3](http://eslint.org/blog/2015/07/eslint-1.0.0-rc-3-released/) right now).

For `disallowKeywordsOnNewLine` I would suggest looking at [brace-style](http://eslint.org/docs/rules/brace-style).

**Comment by zckrs** [comment]
@IanVS thank you for advices :smile: 

PR landed
