### ISSUE TITLE
Improve travis build time

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#154]
We should make sure our travis infra is optimized:
- Runs on container http://docs.travis-ci.com/user/migrating-from-legacy/
- Cache modules: http://docs.travis-ci.com/user/caching/

**Comment by arthurvr** [comment]
> Runs on container http://docs.travis-ci.com/user/migrating-from-legacy/

We already do that. We've got `sudo: false`, which nowdays [isn't needed anymore](https://github.com/sindresorhus/node-module-boilerplate/commit/e5ad4c9c260cabe2e3c038596e210d40b368bea7), but we should keep it as we'll use this generator on repo where Travis is already enabled.

> Cache modules: http://docs.travis-ci.com/user/caching/

Meh, I don't really like that, honestly. It oftentimes causes troubles with dependency updates (Travis doesn't catch sub-dependencies that updated) and thus causing eighter an unstable build or false positives. Mostly the speedup this adds is not too big anyways.

**Comment by zckrs** [comment]
@arthurvr
> Runs on container http://docs.travis-ci.com/user/migrating-from-legacy/ 

 We always need `sudo: false`. See  [doc](http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure)
* For repos we recognize before 2015-01-01, linux builds are sent to our standard infrastructure.
* For repos we recognize on or after 2015-01-01, linux builds are sent to our container-based infrastructure.

The first commit of generator-node : May 15, 2013

**Comment by arthurvr** [comment]
@zckrs Yes, but the repos we scaffold with generator-node will be created later ;)

**Comment by zckrs** [comment]
Oh right. You talk about generate [.travis.yml](https://github.com/yeoman/generator-node/blob/master/generators/travis/templates/travis.yml#L1).

Now I'm not sure to understand this issue :anguished:

**Comment by zckrs** [comment]
@SBoudrias 
Improve Travis build time in this repo or in generated [Travis config](https://github.com/yeoman/generator-node/blob/master/generators/travis/templates/travis.yml) ?

**Comment by arthurvr** [comment]
> Improve Travis build time in this repo or in generated Travis config ?

Both. We want to dog food it IIRC.

**Comment by SBoudrias** [comment]
All improvement we list here (and in any tickets) is for the generated code.

This build of this generator-node will be re-generated by itself.

I see there can be issue with cached modules because of the way we do open source. But for production product it might be useful - build times are usually a big issue for companies. I believe we shouldn't totally reject this issue - but we need a better way of using it than the current PR. - Maybe only enabling it if the repo contains a npm-shrinkwrap.json?

**Comment by stevemao** [comment]
:-1: reason is the same as @arthurvr

**Comment by arthurvr** [comment]
> I believe we shouldn't totally reject this issue - but we need a better way of using it than the current PR. - Maybe only enabling it if the repo contains a npm-shrinkwrap.json?

I saw a huge bunch of attempts to solve this (most of them totally overhead and/or ugly) and it never seems to work perfectly. Dependency installations on Travis are generally pretty fast already. Most slow builds are due to slow tests, bad build systems etc.

**Comment by SBoudrias** [comment]
Closing this in favor of #261
