### ISSUE TITLE
Simplify eslint configuration

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#160]
We should be able to simplify our `.eslintrc` by providing a shareable configuration or maybe by reusing parts of [xo configuration](https://github.com/sindresorhus/eslint-config-xo). (maybe we should create a `eslint-config-yeoman` repo if it makes sense)

**Comment by sindresorhus** [comment]
I think https://github.com/sindresorhus/eslint-config-xo-space is pretty close to the Yeoman style (whatever that is). I'm sure we can come to a concordance.

**Comment by SBoudrias** [comment]
FWIW I ran xo yesterday on yeoman-generator so see how far we were, and it came up with a lot of errors. So we're not totally there (I'm all in with making our core stricter, but some rules weren't applying very well).

**Comment by zckrs** [comment]
Since ESLint v1.0.0 we can extend 'eslint:recommended' to simplify configuration.

**Comment by zckrs** [comment]
FYI, I create a repo [eslint-config-yeoman](https://github.com/zckrs/eslint-config-yeoman).

Maybe `yo node:eslint` should just add devDep `eslint-config-yeoman`

**Comment by SBoudrias** [comment]
@zckrs PR away :)

We were also thinking of maybe basing ourselves on `xo` eslint config with some manual overwrites.

**Comment by sindresorhus** [comment]
> We were also thinking of maybe basing ourselves on xo eslint config with some manual overwrites.

The Yeoman style is pretty close to XO, so that would be a good idea. https://github.com/sindresorhus/eslint-config-xo-space

**Comment by zckrs** [comment]
Summary result with 'eslint-config-xo-space'.

![eslint-xo-space](https://cloud.githubusercontent.com/assets/3020368/11623409/0768521a-9ccd-11e5-9b30-18f428b84d03.png)

Should we apply ?

**Comment by zckrs** [comment]
https://github.com/yeoman/generator-node/pull/198
