### ISSUE TITLE
grunt support missing?

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-node#163]
I just updated this generator to find that every thing goes differently.
how can i go back to the grunt backed version?
and this new version seems buggy.

**Comment by sindresorhus** [comment]
It's now using gulp instead of grunt. As for your other question: http://bfy.tw/1EVt

**Comment by calidion** [comment]
@sindresorhus which version is the last stable version using grunt and es5?

**Comment by calidion** [comment]
using 0.7.0 seems good for me.

**Comment by calidion** [comment]
@sindresorhus 
the new version of generator node seems still not mature enough to release it for production.

**Comment by SBoudrias** [comment]
@calidion Feel free to report the issue you run into with the latest version on new bug report (one bug -> one ticket) and we'll fix them.

I've been using the latest version and it's been working great for me. The es2015 support should be working, but it's still a bit of a beta feature, just opt-out of es2015 syntax if you want more stability.
