### ISSUE TITLE
Clean the compiled files destination (dist/) folder on every prepublish

### ISSUE THREAD

**Issue by floydpink** [yeoman/generator-node#173]
First of all, thank you for all the good work with Yeoman and all of the official generators!

When using ES2015 and Babel, it looks like the prepublish does not do a clean on the `dist/` folder and any changes into the folder/file structure (like file renames, new subfolder etc.) would keep both the old structure files and folders also into the npm published package.

Not a big deal (since only the new files would be actively `require`d, but it would be nice to do a clean on the prepublish.

**Comment by arthurvr** [comment]
Yep, that sounds like the desired behaviour. Thanks for the report.

**Comment by melonmanchan** [comment]
I believe this can be closed, as it was fixed in PR #178 , no?

**Comment by arthurvr** [comment]
Sure, thanks!
