### ISSUE TITLE
Add an .npmignore to skip adding all the non-necessary files into the npm package

### ISSUE THREAD

**Issue by floydpink** [yeoman/generator-node#174]
This is an excerpt from the `.npmignore` in one of the modules built using this generator:

```.gitignore
coverage/
.babelrc
.editorconfig
.eslintrc
.gitattributes
.gitignore
.travis.yml
gulpfile.js
```

**Comment by arthurvr** [comment]
It's better to use [`files`](https://docs.npmjs.com/files/package.json#files) in `package.json` (which we already do)
