### ISSUE TITLE
Adding watch/test task

### ISSUE THREAD

**Issue by Toub** [yeoman/generator-node#177]
What about adding a gulp task to automatically running the tests when files changed:

```javascript
gulp.task('auto-test', function() {
    gulp.watch(['lib/**', 'test/**'], ['test']);
});
```

**Comment by SBoudrias** [comment]
@Toub You should send a PR!

**Comment by Toub** [comment]
Ok, I will give a try next time I am using this generator.

**Comment by hemanth** [comment]
@Toub checkout the branch [gulp-auto-test](https://github.com/yeoman/generator-node/tree/gulp-auto-test)

**Comment by Toub** [comment]
Hi,
Yes, that's the idea.
But there is also an other point to consider. In case of js error, watch will stop and we will have to run tests task again.
@see https://github.com/gulpjs/gulp/issues/216

Sorry but I can't checkout or test now.
