### ISSUE TITLE
ESLint style rules changes

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#187]
There's some rule I dislike we're enforcing in the generated eslintrc. Mostly because they're kind of limiting and doesn't really matter. Here they are:

1. We're disallowing dangling underscore (`no-dangling-underscore`)
2. We're disallowing `== null` (`eqeqeq `)
3. We're on node, so we need `no-console` to be turned off
4. The indent verification seems broken for `switch()` statement. I think we want `indent: [2, 2, {"SwitchCase": 1}]`

**Comment by canercandan** [comment]
:+1:
