### ISSUE TITLE
Provide option/prompt choice for Gulp4 

### ISSUE THREAD

**Issue by zckrs** [yeoman/generator-node#196]
What do you think about create a template gulpfile with Gulp4 ?

**Comment by SBoudrias** [comment]
How far is it from being actually released?

**Comment by sindresorhus** [comment]
We should wait until it's officially released.

**Comment by zckrs** [comment]
I dont know if one day Gulp4 will be released :p 

But 4.0.0-alpha.2 work and IMO the stable version will not change API.

A option with a alpha warning can be acceptable ?

**Comment by mischah** [comment]
More than a year later … No release of Gulp 4 😕 

Closing this since Gulp is gone with the next release of generator-node.
