### ISSUE TITLE
`pre-test` need babelify?

### ISSUE THREAD

**Issue by hemanth** [yeoman/generator-node#199]
`gulp-instanbul` issue? 

//cc @SBoudrias 

[Example](https://travis-ci.org/hemanth/blood-donor/jobs/95334124#L328).

**Comment by SBoudrias** [comment]
Are you pre-compiled to es5?

**Comment by SBoudrias** [comment]
Because according to the trace we see this is the raw file and not the babel compiled file: `hemanth/blood-donor/lib/cli.js`

**Comment by hemanth** [comment]
Yes I have used the `prepublish` task and published what's there in the dist.

I would expect a `.pipe(babel())` in the gulp test task.

**Comment by mischah** [comment]
Babel and Gulp and Istanbul are gone with the next release.
