### ISSUE TITLE
Upgrade `travis` conf.

### ISSUE THREAD

**Issue by hemanth** [yeoman/generator-node#200]
The `.travis.yml` generated with `generator-travis` is pretty outdated?

```
language: node_js
node_js:
 - v5
 - v4
- '0.12'
- '0.10'
```

Travis [fails](https://travis-ci.org/hemanth/blood-donor/jobs/95328879#L95) to run with the above conf.

I still vote for have travis generator within `generator-node`

//cc @SBoudrias

**Comment by SBoudrias** [comment]
I don't see how that's related?

**Comment by hemanth** [comment]
Yes, that fail is related to #199 but what must be the apt travis conf and any reason for replying on the `travis-generator` dep?

**Comment by SBoudrias** [comment]
The conf looks alright to me. You have an unrelated issue.

**Comment by hemanth** [comment]
Putting it in a better fashion at #201
