### ISSUE TITLE
FR: Provide `cli`script creation support.

### ISSUE THREAD

**Issue by hemanth** [yeoman/generator-node#202]
Along with `lib/index.js` based on the user option it would be good to have `lib/cli.js` and bin path in `package.json` as well.

**Comment by SBoudrias** [comment]
We have it https://github.com/yeoman/generator-node/blob/master/generators/cli/index.js

**Comment by hemanth** [comment]
Oh, I didn't not `yo node` inquiring me for that, may be a version mess up on myside.

**Comment by SBoudrias** [comment]
You'd want to run `yo node --cli`

**Comment by hemanth** [comment]
Alright, `cli (Boolean, default false) include or not a lib/cli.js file.`
