### ISSUE TITLE
gulp is too slow, options for both grunt and gulp

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-node#205]
gulp is very slow and unpredictable, while grunt is very stable.

it would be better to provide options for both.

**Comment by SBoudrias** [comment]
What issues have you run into?

**Comment by calidion** [comment]
it seems because of this issue
https://github.com/yeoman/generator-node/issues/206
which is misleading.

**Comment by calidion** [comment]
but it would be very nice to have both.

**Comment by SBoudrias** [comment]
Closing this one as it seems related to your canonical issue.
