### ISSUE TITLE
shows no coverage info and test info when successfully passed.

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-node#206]
[02:25:53] Using gulpfile gulpfile.js
[02:25:53] Starting 'static'...
[02:25:53] Starting 'pre-test'...
[02:25:55] Finished 'pre-test' after 1.55 s
[02:25:55] Starting 'test'...
[02:26:28] Finished 'static' after 34 s

should be told of number of passed tests and coverage info of the test.

**Comment by SBoudrias** [comment]
Okay, this seems to happens when an import error happen somewhere.

It's very annoying and we totally should fix.

**Comment by calidion** [comment]
@SBoudrias 
I have made a pulll request to solve problems which are caused by mocha testing errors.
https://github.com/yeoman/generator-node/pull/207

**Comment by calidion** [comment]
by adding throw err ,
finally i find out where is wrong..

**Comment by SBoudrias** [comment]
Anyone have feedback as to how to fix Gulp when errors occurs outside the pipe?

**Comment by calidion** [comment]
You must throw Error and stop execution.
because all of the following steps are invalid without a successful code execution.

**Comment by germanviscuso** [comment]
I'm doing this in gulpfile.js:

```
var gutil = require('gulp-util');

gulp.task('test', ['pre-test'], function (cb) {
  var mochaErr;

  gulp.src('test/**/*.js')
    .pipe(plumber())
    .pipe(mocha({reporter: 'spec'}))
    .on('error', function (err) {
      mochaErr = err;
      throw new gutil.PluginError({
        plugin: 'test',
        message: err
      });
    })
    .pipe(istanbul.writeReports())
    .on('end', function () {
      cb(mochaErr);
    });
});
```

**Comment by SBoudrias** [comment]
v2.0 changed the build system from gulp + gulp-mocha to jest. There was a lot of problems with gulp-mocha, latest master should be more stable.
