### ISSUE TITLE
mocha options not working?

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-node#208]
I use the current new version generator,
inside <code>test</code> directory, i place the <code>mocha.opts</code> file as follows.
```mocha
--reporter list
--ui bdd
--timeout 100000
```
but i still got the error:

```bash
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

how to enable mocha options?

**Comment by calidion** [comment]
https://github.com/yeoman/generator-node/pull/207
1.enabled mocha.opts
2.throw err where execution can not be continued and test coverage is not accurate .
thanks.

**Comment by SBoudrias** [comment]
As you saw, pass the option in the gulp task.

If you feel we're missing some options that should be there by default, please send a PR.

**Comment by SBoudrias** [comment]
Also, you can see the request on the gulp-mocha project https://github.com/sindresorhus/gulp-mocha/issues/44

**Comment by calidion** [comment]
@SBoudrias 
do u mean i should remove the error thrown code ? and file a new PR?
