### ISSUE TITLE
gulp breaks when executed yo node:cli

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-node#209]
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Unable to parse lib/cli.js

Line 1: Unexpected token ILLEGAL

**Comment by SBoudrias** [comment]
What did you run?

**Comment by calidion** [comment]
```bash
yo node:cli
gulp
```
this error is thrown inside instanbul.

**Comment by eddiemonge** [comment]
What version of the generator? Can you try it again now please? What do you mean by:

> this error is thrown inside instanbul.

**Comment by thiagohmoreira** [comment]
I'm having same issue, but created the app with `yo node --cli` and error message when running `npm test` is:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unable to parse C:\NodeTest\lib\cli.js

Line 1: Unexpected token ILLEGAL
```

Node v6.5.0 / NPM v3.10.3 / YO v1.8.5

**Comment by fega** [comment]
You can use "gulp-replace" before istanbul 

.pipe(replace('#!/usr/bin/env node', ''))

**Comment by mischah** [comment]
Closing this since Gulp and istanbul are  gone with the next release of generator-node.
