### ISSUE TITLE
Git remote URL setting

### ISSUE THREAD

**Issue by MaximAbramchuck** [yeoman/generator-node#219]
When I was generating a package I faced the next issue:

I named my package like 'foobar', but my Github reponame was 'foobar-nodejs'.
I did an initial commit, tried to add a new remote repo named 'origin' but realised that the remote with the same name is already created. I tried to remove it doing `git remote remove origin` and `git remote rm origin` but it did not help. So, I had to remove the whole `.git` folder and init git repo again.
According to the generator sources (`lib/generators/git/index.js:58`) the remote url is formed like:
`repository = this.options.githubAccount + '/' + this.options.name;`

So, if my package name and reponame is not equal, I need to remove the whole `.git` folder and initialize it again.

I think it's kind of weird. Maybe we should just remove this remote url setting feature?

**Comment by SBoudrias** [comment]
Well, you're having an edge case with your repo/package name not being the same. I think the current behavior is still the best for the majority of people.

Git gives a way to change a remote url, that's what you wanted to do:

```sh
git remote set-url origin git://new.url.here
```
