### ISSUE TITLE
CLI help should use template literal when using Babel

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-node#220]
https://github.com/yeoman/generator-node/blob/d98460b68fcdfa5fc393c12452a8591a3090a890/generators/cli/templates/cli.js#L11-L23

See: https://github.com/sindresorhus/trash-cli/blob/master/cli.js#L7-L14

Instead of using lodash templates it should just use different files when Babel is chosen as a lot is different.

Babel mode should also use `const` instead of `var`.

**Comment by hemanth** [comment]
:+1:  was thinking of the same in `meow` as well.

**Comment by mischah** [comment]
Babel is gone 👋🏼

… at least for now. See 602e2507037903a6597bdc042a12d9f45f323bf4.
