### ISSUE TITLE
Generator is too slow offline

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#221]
We're making some requests to the github API to get data about the user. The timeout on these request is way to long and makes the generator unusable when offline.

We need to reduce the timeout to < 1-2s

**Comment by alexsantos** [comment]
At work I have a proxy configured on my Ubuntu box and can use git, bower or npm but this generator seems that isn't using it.

**Comment by alexsantos** [comment]
I've been digging on the source code and my problem starts on checking for an existing name for the package on NPM - so the problem is with the way the package "npm-name" is trying to achieve it. It uses "got" so it can't use the .npmrc configuration, for instance. Is there a better way for this?

**Comment by SBoudrias** [comment]
@alexsantos open an issue on `npm-name`.

**Comment by alexsantos** [comment]
@SBoudrias Ok :+1:

**Comment by SBoudrias** [comment]
@alexsantos I don't see anywhere where the proxy issue is dismissed. The project is welcoming PR to fix this.

OSS authors works on issues they're interested in, they're not your employees. If you want proxy support now, then it's up to you to send a PR.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/got/issues/79

**Comment by alexsantos** [comment]
@SBoudrias Thanks for getting back on this. I will look on this, just wondering if there was already some kind of idea for a new approach or not.
@sindresorhus :+1:

**Comment by SBoudrias** [comment]
Tested this offline and it seemed the performance was way better now.

Proxy support is still an open issue on Node side; but we won't be fixing this directly inside generator-node; so I'll close this issue as there's nothing more we can do here.
