### ISSUE TITLE
Generate AVA tests?

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#222]
gulp-mocha is not working super well, and I kinda like the [ava](https://github.com/sindresorhus/ava) syntax.

Any opinions?

(cc @sindresorhus)

**Comment by zckrs** [comment]
I like AVA. 
Should we replace gulp-mocha or just add a default option for AVA ?

**Comment by SBoudrias** [comment]
I'm up for debate. My initial idea is to just replace, but I'm open to other options.

FWIW, we need to make sure we can get good coverage working. And also, we need to make sure this is going to work well with the Yeoman context; one thing I'm concerned about is `yeoman-test` and how AVA `t.plan()` would play with our custom asserts.

**Comment by sindresorhus** [comment]
:+1: gulp-mocha is pretty bad (I made it. Though, it's because the Mocha API is completely broken).

**Comment by hemanth** [comment]
@sindresorhus I am curious to know what part of Mocha API is broken? As most of my modules so far are relying on it.

**Comment by sindresorhus** [comment]
@hemanth The programmatic API, not the one you use in tests.

**Comment by hemanth** [comment]
@sindresorhus Oh, alright.

**Comment by SBoudrias** [comment]
@sindresorhus do you know of any AVA project setup with test coverage we could take as example?

**Comment by sindresorhus** [comment]
@SBoudrias Yup, and it's very easy. See https://github.com/sindresorhus/pageres/blob/aa4bf7997a14ab4f37f0150323dd46718268b2d4/package.json#L18 and https://github.com/sindresorhus/pageres/blob/aa4bf7997a14ab4f37f0150323dd46718268b2d4/.travis.yml#L7

Full instructions here: https://github.com/bcoe/nyc#integrating-with-coveralls

**Comment by iamstarkov** [comment]
can anybody show yo generator with ava tests?

**Comment by sindresorhus** [comment]
@iamstarkov https://github.com/sindresorhus/generator-nm/blob/master/test.js

**Comment by alexlafroscia** [comment]
In case anyone is curious, I made another Yeoman generator that uses Ava instead of Mocha and Gulp

https://github.com/alexlafroscia/generator-skatejs/blob/master/test/generators/app.js

The tests definitely run faster, still get coverage out-of-the-box if you just run `nyc ava` instead of `ava` (not other config required, from what I can tell).

The only caveat is that you have to run any tests that leverage `yeoman-test`'s helpers using `test.serial`, otherwise you get errors about there being too many listeners being added.

**Comment by SBoudrias** [comment]
I'd still be happy to merge a PR offering the option to generate AVA tests in the future.

With v2.0 release, we got rid of gulp. I'll close this ticket given the main issue with unstable build is fixed, and we don't plan to actively work on adding an extra test framework ourselves. Thanks :)
