### ISSUE TITLE
Cannot find module 'estraverse-fb' running gulp  after module initialization.

### ISSUE THREAD

**Issue by gbahamondez** [yeoman/generator-node#233]
Generate a project running generator-node from yeoman inside a directory with name node-gen.

```sh
$ cd node-gen
$ gulp
```

Gives me  **Error: Cannot find module 'estraverse-fb'**

Options:
<img width="479" alt="screen shot 2016-03-09 at 1 36 14 am" src="https://cloud.githubusercontent.com/assets/3533121/13625549/92c3c23c-e597-11e5-9cfb-7e58e33a8603.png">

Error:
<img width="953" alt="screen shot 2016-03-09 at 1 38 50 am" src="https://cloud.githubusercontent.com/assets/3533121/13625558/b6779082-e597-11e5-8d07-b85ea248d1d2.png">

**Comment by SBoudrias** [comment]
Can you try running again `npm install`?

**Comment by gbahamondez** [comment]
@SBoudrias hi, thanks for your answer , i was trying with that, but not works, i managed it to work  with 
```sh
$ npm install estraverse-fb
```
But that shouldn't be necessary, i think, since all the other packages and dependencies are intalled automatically.

Looks like a missing dependency in some package.json file.

**Comment by zckrs** [comment]
Bug with ESLint v2.3.0

Issue https://github.com/eslint/eslint/issues/5476

**Comment by ajsb85** [comment]
I fix it with `npm install estraverse-fb --save-dev`

**Comment by hemanth** [comment]
Are we still facing this?

**Comment by SBoudrias** [comment]
Eslint marked it as fixed. So I'll close here.

**Comment by gbahamondez** [comment]
working, just fine, recently tested, thanks.

**Comment by germanviscuso** [comment]
Still getting this problem when running 'npm test'. Latest version of generator-node which from package.json I can see it's using eslint 2.1.0.
I'm using node v4.2.1 and npm v3.5.2
