### ISSUE TITLE
Conflict using different names in github and npm

### ISSUE THREAD

**Issue by ajsb85** [yeoman/generator-node#234]

**Comment by SBoudrias** [comment]
Can you provide a better description of your issue..?

What's the expected behavior? What's happening currently?

**Comment by ajsb85** [comment]
Hi @SBoudrias 
I have a module with a name and a git repository with another name.

An example to fix it is add another step in the terminal wizard to use another name in the repository.

**Comment by SBoudrias** [comment]
Wouldn't fixing this yourself be a better solution? I feel like for most user the default behavior is good enough.

Only thing you need to do is `git remote set-url origin your-repo`.

**Comment by ajsb85** [comment]
And change the README.md and the package.json
I will make fork then, and build my own generator, thanks.
