### ISSUE TITLE
EsLint dependency causes error in default gulp tasks.

### ISSUE THREAD

**Issue by aeschylus** [yeoman/generator-node#235]
`Error: Cannot find module 'estraverse-fb'`... etc. 

See: 
- https://github.com/eslint/eslint/issues/5476
- https://github.com/babel/babel-eslint/issues/267

The practical effect is that it is not possible to test any module created with this generator.

**Comment by aeschylus** [comment]
Given how recently this issue was filed, I imagine they are really the same thing: #232

**Comment by SBoudrias** [comment]
I believe that's fixed if you update your dependencies. Someone broke something in the dep change.

`npm update && npm test`
