### ISSUE TITLE
Can't make a local generator

### ISSUE THREAD

**Issue by kristianmandrup** [yeoman/generator-node#242]
Try to follow this guide: http://yeoman.io/authoring/

I cloned the repo, renamed the package name:

`"name": "generator-node-ES2017"`

then ran `npm link`

However I get this error:

`You don't seem to have a generator with the name node-es2017 installed`

What am I missing!?

**Comment by SBoudrias** [comment]
Did you try running `yo doctor`

If that doesn't work, try running `DEBUG=yeoman:* yo node-ES2017`
