### ISSUE TITLE
Fix: Tests with local trevor

### ISSUE THREAD

**Issue by frank-dspeed** [yeoman/generator-node#246]
at present travis.yml includes v5 v6 v8

this repos don't exist in global node namespace of docker they are called 6 5 4

**Comment by frank-dspeed** [comment]
we should refactor the travis build to use docker also !

https://docs.travis-ci.com/user/docker/

**Comment by hemanth** [comment]
`travis.yml` expects `v` and yeah with docker support something like trevor for local testing will be useful.

**Comment by frank-dspeed** [comment]
We only need to change the travis yml i will assign that to my self then the build works online with docker and offline no changes needed

**Comment by SBoudrias** [comment]
Should be okay now.
