### ISSUE TITLE
Keep babel or not?

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#250]
I feel the babel flow is a bit of a tooling overhead - especially given Node 4 support most of es6.

What's the feeling? Keep or let go?

**Comment by hemanth** [comment]
Rather than letting go, we can make it optional?

**Comment by calidion** [comment]
how about use typescript instead of babel?

**Comment by mischah** [comment]
Babel is gone 👋🏼

… at least for now. See 602e2507037903a6597bdc042a12d9f45f323bf4.
