### ISSUE TITLE
Dropping gulp

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#251]
I feel lately a lot of tooling come more battery included which are making build processes simpler. I feel like we might be able to drop most of our gulp pipeline in favor of such simpler tools (and in the future prefer/select tools with lower configuration overhead).

**Comment by hemanth** [comment]
A big 👍

**Comment by zckrs** [comment]
>in favor of such simpler tools

What tools do you think?
And maybe keep gulp optional

**Comment by hemanth** [comment]
> What tools do you think?

Well, `npm scripts` with tiny helper modules?

**Comment by zckrs** [comment]
Why not.

Currently we have:
* gulp-eslint :arrow_right: eslint
* gulp-istanbul :arrow_right: replace by nyc ?
* gulp-line-ending-corrector :arrow_right: line-ending-corrector (but no cli avaible)
* gulp-mocha :arrow_right: replace by ava ?
* gulp-nsp :arrow_right: nsp
* gulp-coveralls :arrow_right: coveralls

**Comment by hemanth** [comment]
For line-ending-corrector CLI there is `crlf2lf`

**Comment by zckrs** [comment]
`crlf2lf` take a directory and we only need to convert for cli.js

**Comment by hemanth** [comment]
Ha, right; Time for a new module ;) ?

**Comment by SBoudrias** [comment]
Any feeling about replacing mocha with jest? https://github.com/SBoudrias/generator-jest

The test API itself is really similar, and it has built-in coverage (and babel support).

**Comment by hemanth** [comment]
`jest` is a good candidate, so is `ava` ?

**Comment by SBoudrias** [comment]
Does ava automatically compile with babel and provide coverage?

**Comment by hemanth** [comment]
babel yes, coverage hmm `nyc`

**Comment by mischah** [comment]
It’s done 👌 

See [commit history](https://github.com/yeoman/generator-node/commits/master).
