### ISSUE TITLE
Bypass eslint

### ISSUE THREAD

**Issue by stropitek** [yeoman/generator-node#252]
I'm writing a yeoman generator that composes with generator-node
I'd like to generate a node project with my own eslint configuration. How can I achieve that? My approach was to generate my own eslint dependencies and configuration, but generator-node does not allow to deactivate the eslint sub-generator

I'm willing to PR

**Comment by SBoudrias** [comment]
@stropitek can't you just overwrite the file generator-node creates?

**Comment by stropitek** [comment]
@SBoudrias yes I could do that. I thought though it would be more handy to have the option right out from generator-node

**Comment by stropitek** [comment]
What I mean is that if other users use this package to create their own generator, they will likely want to have their custom eslint configuration, so the option would come in handy

**Comment by SBoudrias** [comment]
@stropitek I just feel overwriting the config yourself is easier and doesn't require learning about an extra option.

I'm not opposed to adding the option, but I usually think less configuration/api surface is better.

**Comment by stropitek** [comment]
Sure, no need to debate too much over this :smiley:. Thanks for the insights.
