### ISSUE TITLE
The name above already exists on npm, choose another?

### ISSUE THREAD

**Issue by tarranjones** [yeoman/generator-node#254]
I received this prompt 
```sh
[? The name above already exists on npm, choose another?
```
Whilst searching for an alternative name I didn't come across the name i wanted (cmd-cli) so I checked the package homepage (https://www.npmjs.com/package/cmd-cli) which was throwing a 404.
I attempted `npm publish` expecting it to fail but it worked. 

Either I have misunderstood what "The name above already exists on npm" is supposed to mean or the generator is reporting that a package with that name already exists when it doesn't.

**Comment by SBoudrias** [comment]
Looks like something went wrong.

I still use the generator often and haven't run into this issue before. Might be an edge case with the npm api...

Either way, we should investigate further.

**Comment by SBoudrias** [comment]
Not sure how we can go about investigating this, no one else reported this issue. So I'll close and we can reconsider if this become a more consistent issue.
