### ISSUE TITLE
Release new version of generator-node

### ISSUE THREAD

**Issue by mischah** [yeoman/generator-node#257]
Hej, a new version is needed to fix an issues with the currently released version of `generator-generator`. See yeoman/generator-generator#183.

Is there anything I can help with to roll `generator-node` v2 out to the streets? 😘

 Cheers, Michael

**Comment by SBoudrias** [comment]
Can you test latest master? I'm unsure what was still missing at the moment

**Comment by mischah** [comment]
Sure, will do.

**Comment by SBoudrias** [comment]
Checked it tonight and I think it's mostly good.

The only main thing missing we had before is the crlf/lf corrector for cli programs. You can read a bit about that conversation https://github.com/yeoman/generator-node/issues/251

Might not be a blocker, but it'd be a good addition.

**Comment by SBoudrias** [comment]
We eventually should refactor code to idiomatic es6 generators. But that won't be a release blocker.

**Comment by mischah** [comment]
[line-ending-corrector](https://github.com/iShafayet/line-ending-corrector) also has a CLI. Im going to prepare a PR to get that in tonight.

> We eventually should refactor code to idiomatic es6 generators. But that won't be a release blocker.

I would prefer an early release without that for now. Because I really want generator-generator to be fixed 😬 

cc/ @hemanth @zckrs

**Comment by SBoudrias** [comment]
Okay, release `v2.0`

I don't really have time to write the release note right now. Let's close this ticket once that's done.

**Comment by hemanth** [comment]
👍

**Comment by mischah** [comment]
Wrote release notes. See https://github.com/yeoman/generator-node/releases/tag/v2.0.0 

… hope I got all breaking changes.

@SBoudrias 
Can I delete the branch [fix-es2015](https://github.com/yeoman/generator-node/tree/fix-es2015)?

**Comment by SBoudrias** [comment]
Yup, we can delete that branch.

**Comment by mischah** [comment]
> Yup, we can delete that branch.

Done :octocat:
