### ISSUE TITLE
[FEAT] Git hooks

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#259]
I think it'd be great to setup pre-commit/pre-push hooks automatically.

I think [Husky](https://github.com/typicode/husky) is a great option. What I have in mind is:

- _pre-commit_: run `eslint --fix`
- _pre-push_: run full `npm test`

My only concern is husky (and other node based pre-commit hooks) will run on all files and not only modified files. This might not be an issue with new projects, but it's a required feature for legacy projects. We don't need to address this right away, but it'd be something to keep in mind for the future.

**Comment by mischah** [comment]
Good idea. When working in a team the following also might be helpful:
+ post-merge: `npm install`
