### ISSUE TITLE
[FEAT] Use yarn by default

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#261]
Related to #154, we could use Yarn by default.

Might be good to do https://github.com/yeoman/generator/issues/991 first, then start using yarn here.

**Comment by hemanth** [comment]
Are we still planning to do this? Given that the latest `npm` is pretty fast.

**Comment by mischah** [comment]
I don’t feel the need like a couple of months ago.

Would be interesting to have a PR targeting this nonetheless to see if it’s worth.

**Comment by SBoudrias** [comment]
I'll close this one as I think npm catched up okay.
