### ISSUE TITLE
Remove `--ignore-path` option in ESLint npm script

### ISSUE THREAD

**Issue by mischah** [yeoman/generator-node#263]
It’s now written into the package.json like this:

```
scripts: {
  pretest: 'eslint . --ignore-path .gitignore --fix'
}
```

See [/generators/eslint/index.js:L31](https://github.com/yeoman/generator-node/blob/master/generators/eslint/index.js#L31)

Which has the effect that a `.eslintignore` file would be ignored.

See ESLint [docs](http://eslint.org/docs/user-guide/configuring#using-an-alternate-file):
> Keep in mind that specifying --ignore-path means that any existing .eslintignore file will not be used

Related to: yeoman/generator-generator#188

**Comment by SBoudrias** [comment]
Maybe we should duplicate the .gitignore content in another eslintignore file

**Comment by mischah** [comment]
Jup. Even though node_modules doesn’t need to be in .eslintignore. 

But we would need an additional template file for eslintignore anyway:

```
/generators/eslint/templates/eslintignore
```

That way generator-node would provide that file and yeoman/generator-generator#188 could be closed, right?

**Comment by SBoudrias** [comment]
Yeah, in generator-generator you'd be able to use `this.fs.append()`
