### ISSUE TITLE
[Bug] Freezes when using node 8.1.0

### ISSUE THREAD

**Issue by keenahn** [yeoman/generator-node#265]
```
macOs Sierra 10.12.5
node 8.1.0
yo 2.0.0
generator-node 2.1.0
```

This freezes at the line asking for description. I can't even `ctrl+c` out of it. I have to use pkill.
```
k@mbp:~/s/sandbox 7:56:20$ node --version && yo --version
v8.1.0
2.0.0
k@mbp:~/s/sandbox 7:56:58$ yo node
? Module Name asdfasdf
? Description 
```

Works fine with node 7.1.0 and yo 2.0.0

**Comment by mischah** [comment]
This is a regression in Node. You should use Node 7 as long as this isn’t fixes.

@SBoudrias Do you have a link to the issue over here?
https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20

Didn’t find it spontaneously.

**Comment by SBoudrias** [comment]
Latest Node release fix the issue.
