### ISSUE TITLE
Allow using scoped package names

### ISSUE THREAD

**Issue by Myhlamaeus** [yeoman/generator-node#272]
When using a [scope in the package name](https://docs.npmjs.com/getting-started/scoped-packages), both the `@` and the `/` are stripped from the name; `@scope/project-name`, for example, gets turned into `scope-project-name`. This makes it quite hard to use this generator for scoped packages (including all private packages), as the name has to be altered in different ways at different places.

## Things to consider
- Should the package name and its scope be treated separately—adding, for example, an option `scope` to supply the scope?
- What should happen to `@scope/` if the package name and scope are not treated separately?
- Should the package name really always be turned into kebab-case? `example.com`, for example, gets turned into `example-com` through it.
- Should the scope appear in the default git remote (i.e. in the GitHub repository’s name)?
- Some of the links in the generated `README.md` reference the package, and some reference the repository (e.g. `npm-url` references the package and `travis-url` the repo)

**Comment by SBoudrias** [comment]
We should handle scoped packages way better.

What's the behavior you would expect?

**Comment by SBoudrias** [comment]
I think a piece of the solution would be to get rid of the kebab case modification and validate npm package name with https://www.npmjs.com/package/validate-npm-package-name instead.

**Comment by SBoudrias** [comment]
I made a WIP PR to fix some of those issues. Still need to work on the URL issue you pointed out.

Can you check the branch out and tell me if it fixes most of your issues?
