### ISSUE TITLE
Usage behind proxy

### ISSUE THREAD

**Issue by MarcoScabbiolo** [yeoman/generator-node#274]
To allow the generator (and all other generators that depend on it) to be used behind a proxy we could add   [caw](https://www.npmjs.com/package/caw) to the request made by `github-username`.

`github-username` doesn't currently support the `agent` property of the [`http-request` options](https://nodejs.org/api/http.html#http_http_request_options_callback) but I've made a [PR](https://github.com/sindresorhus/github-username/pull/8) to achieve this.

There might other modules that need `caw` but this is at least a starting point.

**Comment by SBoudrias** [comment]
A PR would be awesome once the dependencies are ready :)

**Comment by MarcoScabbiolo** [comment]
Sure!

**Comment by MarcoScabbiolo** [comment]
I'll be working on [this fork](https://github.com/MarcoScabbiolo/generator-node) until all of the dependencies are ready.

Sadly I had to make a [parallel github-username](https://github.com/MarcoScabbiolo/github-username-options) because [my PR](https://github.com/sindresorhus/github-username/pull/8) was rejected, see the PR if you want more details.

**Comment by SBoudrias** [comment]
@MarcoScabbiolo did you consider making a PR to `got`?

**Comment by SBoudrias** [comment]
I'll close this one as we merged the tunnel on `yo`. Thanks again for the help getting this out and following with issues afterwards!
