### ISSUE TITLE
cannot replace 'pretest' script.

### ISSUE THREAD

**Issue by jhessin** [yeoman/generator-node#279]
I have been scratching my head for some time on this one. I'm trying to extend this generator to use coffeescript but for some reason the pretest script is not being overwritten. Eslint is nice, but it isn't very useful when you are working with coffeescript instead.

Here is my index.coffee install script (straight exported to index.js)

```coffeescript
path = require 'path'
Generator = require 'yeoman-generator'
askName = require 'inquirer-npm-name'
_ = require 'lodash'
extend = require 'deep-extend'
mkdirp = require 'mkdirp'
chalk = require 'chalk'
yosay = require 'yosay'

module.exports = class extends Generator
  constructor: (args, opts)->
    super(args, opts)

    @argument 'name',
      type: String
      required: false

    if @options.name?
      @props = @options
    else
      @props = {}
    return

  prompting: ->
    if not @props.name?
      askName {
        name: 'name'
        message: 'Your generator name'
        default: path.basename(process.cwd())
      }, this
      .then (props) =>
        @props.name = props.name
    return
  default: ->
    if path.basename(@destinationPath()) isnt @props.name
      @log "Your generator must be inside a folder named #{@props.name}\n\
      I'll automatically create this folder."
      mkdirp @props.name
      @destinationRoot @destinationPath(@props.name)
    readmeTpl = _.template @fs.read(@templatePath('README.md'))

    @composeWith require.resolve('generator-node/generators/app'), {
      name: @props.name
      boilerplate: false
      projectRoot: 'lib'
      skipInstall: true
      readme: readmeTpl @props
    }
    return

  writing: ->
    pkg = @fs.readJSON @destinationPath('package.json'), {
      scripts:
        pretest: 'coffeelint src && gulp'
        install: 'gulp'
      'lint-staged':
        '*.coffee': [
          'coffeelint',
          'git add'
        ]
    }

    pkg.keywords = pkg.keywords or []
    pkg.keywords.push 'CoffeeScript'

    @fs.writeJSON @destinationPath('package.json'), pkg

    @fs.copy @templatePath('gulpfile.coffee'),
      @destinationPath('gulpfile.coffee')

    @fs.copy @templatePath('src'),
      @destinationPath('src')
    return

  install: ->
    @yarnInstall [
      'coffeescript', 'gulp'
      'babel-core', 'babel-preset-env'
      'gulp-coffee', 'gulp-cson'
      'gulp-sourcemaps'
    ], dev: true
    return

```

And the scripts section after running the generator:

```json
"scripts": {
    "pretest": "eslint .",
    "prepublishOnly": "nsp check",
    "precommit": "lint-staged",
    "test": "jest",
    "install": "gulp"
  },
```

**Comment by SBoudrias** [comment]
The issue is that your generator `writing` sequence is scheduled to run before `generator-node` own writing sequence. http://yeoman.io/authoring/running-context.html

The fix in this case would be to break your generator into 2. A top level generator who'll compose with both generator-node and a new generator you create to add your coffeescript specific configuration.

It would look like this:

1. Top level generator: handles the prompt + composeWith calls
2. composeWith generator-node first
3. composeWith your new generator second

**Comment by jhessin** [comment]
This still doesn't work. I now have the generator split into a subgenerator, but for some reason it runs generator-node after my subgenerator even though it calls my generator second.

**Comment by jhessin** [comment]
Okay. I was able to get it working by calling composeWith generator-node from default and then calling composeWith my subgenerator from the writing phase. I don't think this is how it's supposed to work though.

**Comment by SBoudrias** [comment]
@jhessin Hey, the solution you described last is how the system works right now.

It is a little verbose right now for really simple use case, but usually works fine with more complex workflow (for example in the case of [generator-generator](https://github.com/yeoman/generator-generator))

A long time ago we discussed potential simplification to composability, but there wasn't too much community excitement towards the feature - and major refactor risked splitting the community, so it never came to fruition. https://github.com/yeoman/generator/issues/894
