### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by BhuwanDevshali** [yeoman/generator-node#283]
HI,

When I try to run 'yo node' o the CLI, it gives me the folowing error:

![image](https://user-images.githubusercontent.com/1539288/49282155-75a77700-f4b4-11e8-8954-4bbd3bae8730.png)

What could be the reason? Am i doing anything wrong?

**Comment by SBoudrias** [comment]
Hey, I just tried to reproduce this bug, but I was unable to. Maybe try to reinstall? Or try running with `npm create yo node`?

**Comment by BhuwanDevshali** [comment]
I tried using 'npm create yo node' and again got the same error

**Comment by BhuwanDevshali** [comment]
I noticed that when I try to name the module with something that starts with an upper case letter, it throws an error. If I try with a name starting with lower case, the error disappears but it gets stuck there.
![image](https://user-images.githubusercontent.com/1539288/49362268-60c12280-f704-11e8-942e-0569e1b45576.png)

**Comment by knightkill** [comment]
I second this!
