### ISSUE TITLE
Code coverage integration?

### ISSUE THREAD

**Issue by cvrebert** [yeoman/generator-node#59]
Any chance of adding code coverage tool (e.g. Istanbul or jscoverage) integration to the generated modules?

**Comment by stevemao** [comment]
We could put logics in either Gruntfile or .travis.yml. coveralls works very well with travis.

**Comment by SBoudrias** [comment]
This'll be fix as part of https://github.com/yeoman/generator-node/issues/66

I'll close this issue as it's being worked on ATM and almost merged in the generator.
