### ISSUE TITLE
Moving towards yeoman core features

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-node#66]
A couple days ago we started talking about consolidating the yeoman core build system in a reusable module https://github.com/yeoman/yeoman/issues/1440 - This module obviously is `generator-node`.

All the features contained in https://github.com/yeoman/generator will be added or updated to match our internal style.

To make a short list:

- Code coverage
- Coveralls integration
- Unit test (mocha)
- Travis.CI integrtion
- jshint (we also have eslint on yeoman-generator, but we'll make a cut and probably keep only one)
- node-jscs (code style checker)
- jsdoc
- Benchmarks (matcha)
- Security linting (nsp)

Default build will use `gulp`, but we intend to provide the choice between:

- Gulp
- Grunt
- Simpler raw npm build config (only jshint and mocha)

Any requests or comments is welcome! (Help marking this happens is also welcome!)

**Comment by SBoudrias** [comment]
Started working on this on the `node.next` branch.

The goal is to have a series of self contained sub-generators that could be composed with by any other generators.

Basic sub-generators would be:

- travis
- package (ask questions and fill package.json)
- readme (will take a bunch of command line options for badges and stuff)
- editor config
- jshint
- jscs
- git
- build (will ask questions about the tasks we want to run) - initially we can make it just Gulp, but then we'd want three options (gulp, grunt and raw)

**Comment by arthurvr** [comment]
Sounds awesome.

**Comment by SBoudrias** [comment]
@arthurvr feel free to send PRs, the more the merrier!

**Comment by arthurvr** [comment]
@SBoudrias The first one is already opened :lollipop:

**Comment by hemanth** [comment]
Just making a TODO list out of what @SBoudrias [suggested.](https://github.com/yeoman/generator-node/issues/66#issuecomment-90822539)

- [x]  travis

- [ ]  package (ask questions and fill package.json)

- [ ]  readme (will take a bunch of command line options for badges and stuff)

- [x]  editor config

- [x]  jshint

- [ ] jscs

- [ ]  git

- [ ] build (will ask questions about the tasks we want to run) - initially we can make it just Gulp, but then we'd want three options (gulp, grunt and raw)

- [ ] license (I think there's one out there already, we could compose with it)

**Comment by arthurvr** [comment]
I'm on `node:git` ;)

**Comment by arthurvr** [comment]
There we go. PR opened for `node:git`.

**Comment by arthurvr** [comment]
On the `jscs` one but the PR will be for tomorrow.

**Comment by arthurvr** [comment]
You know what? PR opened :tada:

**Comment by arthurvr** [comment]
That was quick! yippee!

**Comment by SBoudrias** [comment]
Started to work on the readme sub-generator

**Comment by SBoudrias** [comment]
With my last PR, the last major roadblock for a first release will be the license sub generator.

There's [generator-license](https://github.com/jozefizso/generator-license) we could update to be composable, but ATM it is not.

We also want to create boilerplate module + boilerplate test generator. With an option to skip them.

Then we need to update our documentation and ideally have a section about how to compose other generators on top of this one.

After, the next step will be:

- [ ] Raw build system option (we could base ourselves on yeoman-environment who's not using Gulp. (see https://github.com/yeoman/environment/commit/d89bdc3a7888d303b485233b5cb0ee597cd624e9#commitcomment-9690814)
- [ ] Ensuring reproducibility (we want to be able to easily re-run this generator on top of older projects and have it updated to the latest version with as few friction as possible)
- [ ] Compose node based official generators on top of this one (`generator-generator` and `generator-gruntplugin`, and even `generator-node`! Let's dog food it). This process should help us improve our composition story, I'm pretty sure we'll need more option and make the code more clever around extending pre-existing files.

**Comment by SBoudrias** [comment]
Couple things we'll need to fix with what we have now:

- [ ] Should include coveralls badge in Readme

**Comment by SBoudrias** [comment]
Made some update to the branch and finished the core things we needed to do before our first release.

Please try it out on your machine and report feedback so we have a first new solid release.

**Comment by arthurvr** [comment]
I just noticed one thingie when running gulp:

```
/Users/arthurvr/code/testing-node-gen/gulpfile.js:49
gulp.task('default', [&#34;static&#34;, &#34;test&#34;]);
                      ^
SyntaxError: Unexpected token &
```

sounds like there's just some bad escaping going on

**Comment by SBoudrias** [comment]
Oh, must be an ejs change. We'll need to output an unescape string there.

**Comment by stevemao** [comment]
Is there anything missing on the list?

**Comment by SBoudrias** [comment]
Nope, I'm in the process of releasing 1.0 in the next few minutes.

**Comment by stevemao** [comment]
:tada:

**Comment by hemanth** [comment]
:+1:

**Comment by kevva** [comment]
:horse:
