### ISSUE TITLE
Add support for .editorconfig

### ISSUE THREAD

**Issue by addyosmani** [yeoman/generator-node#76]

**Comment by hemanth** [comment]
Done, not sure why that was missed!

**Comment by arthurvr** [comment]
I'm not dure if this is what Addy meant. I think he means that the generator doesn't generate an editorconfig file.

**Comment by arthurvr** [comment]
You know what? PR coming

**Comment by hemanth** [comment]
@arthurvr Ah, makes sense, misinterpreted the @addyosmani's message. 

I'm working on it.

**Comment by addyosmani** [comment]
@arthurvr was correct. Thanks both!

**Comment by arthurvr** [comment]
@hemanth Thanks!

**Comment by hemanth** [comment]
Thanks @arthurvr
