### ISSUE TITLE
any reason why variable name in README.md is not in camelCase?

### ISSUE THREAD

**Issue by stevemao** [yeoman/generator-node#79]
var <%= slugname %> = require('<%= slugname %>');

Is this a bug?

**Comment by hemanth** [comment]
No it's not a bug, look at [index.js#L45](https://github.com/yeoman/generator-node/blob/master/app/index.js#L45)

**Comment by stevemao** [comment]
So this is not using camelCase on purpose? Sorry I don't really understand this.

**Comment by hemanth** [comment]
@stevemao Are you facing any issue? That's just a naming convention.

**Comment by stevemao** [comment]
Not really, just think variable names should be camelCase. The ones in the code are camelCased but not in README.md. I have to manually change it every time.

**Comment by stevemao** [comment]
https://github.com/yeoman/generator-node/blob/master/app/templates/cli.js#L4

This is using safeSlugname 

But in README.md it's

var <%= slugname %> = require('<%= slugname %>');

**Comment by stevemao** [comment]
I knew there was a problem :smile_cat:

**Comment by hemanth** [comment]
heh heh, we must use `_.slugify` rather than manually slugifying it.

**Comment by hemanth** [comment]
Ha, we are [L46](https://github.com/yeoman/generator-node/blob/master/app/index.js#L46)

**Comment by stevemao** [comment]
Looks like safeSlugname is camelCased name.

**Comment by hemanth** [comment]
Yes, that was done [here](https://github.com/yeoman/generator-node/pull/21) as a fix, but I still feel that the readme must be `slugname` not safe slug.

**Comment by stevemao** [comment]
Any reason for this?

**Comment by hemanth** [comment]
Readme must not be safe, but rather must be plain slug.

Say if your module is named as `is-mp3` doing a `var is-mp3` is not a vaild literal, so we had to use safe names, that would result in `isMp3` hence we could do `var isMp3 = require('is-mp3')`

**Comment by stevemao** [comment]
Isn't the part in readme sample code?

**Comment by hemanth** [comment]
@stevemao Sorry for the `ping-pong` the readme template must be:

```
var <%= safeSlugname %> = require('<%= slugname %>');

```

Feel free to send a PR.

**Comment by stevemao** [comment]
Sure :smiley:
