### ISSUE TITLE
Source Folder

### ISSUE THREAD

**Issue by gpedro** [yeoman/generator-node#90]
why not create a structure with sources folder?
```
.
├── Gruntfile.js
├── index.js
├── package.json
├── README.md
├── src
│   └── index.js
└── test
    └── test.js
```

/index.js -> exporting require src/index
/Gruntfile.js
```
js: {
    src: ['src/**/*.js']
},
```

**Comment by sindresorhus** [comment]
> /index.js -> exporting require src/index

Why would you add moot boilerplate?

-

Most modules are only one file and it's just a waste to add extra folder nesting. You can easily add it if you need it ;)
