### ISSUE TITLE
ES{6,7} support.

### ISSUE THREAD

**Issue by hemanth** [yeoman/generator-node#95]
Time to add some babel support and use `es6` features wherever we can? 

//cc @addyosmani @SBoudrias @sindresorhus @passy

**Comment by supergray** [comment]
:-1: not everybody likes ecmascript personally i prefer javascript as well

**Comment by arthurvr** [comment]
:+1:! Will submit a PR if everybody agrees ;)

**Comment by huei90** [comment]
+1 Can be optional!

**Comment by SBoudrias** [comment]
@arthurvr if you want to move forward on this, we should take care of this before anything else: https://github.com/yeoman/generator-node/issues/66

**Comment by arthurvr** [comment]
Closing as this was merged into the `node.next` branch.
